name             'ansible'
maintainer       'Josh Guice'
maintainer_email 'jguice@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures ansible'
long_description 'Installs/Configures ansible'
version          '0.1.0'
